language: python
python:
    - "2.7"

env:
    - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
    - PLATFORMIO_PROJECT_DIR=examples/arduino-webserver
    - PLATFORMIO_PROJECT_DIR=examples/arduino-wifiscan
    - PLATFORMIO_PROJECT_DIR=examples/native-sdk
    - PLATFORMIO_PROJECT_DIR=examples/simba-blink

install:
    - pip install -U https://github.com/platformio/platformio/archive/feature/platformio-30.zip
    - platformio platform install file://.

script:
    - platformio run -d $PLATFORMIO_PROJECT_DIR
